set NITROSDK_ROOT=%CD%\NitroSDK
set NITROSYSTEM_ROOT=%CD%\NitroSystem
set NITROWIFI_ROOT=%CD%\NitroWiFi
set NITRODWC_ROOT=%CD%\NitroDWC
set NITROLIBVCT_ROOT=%CD%\libVCT
set NITROVCT_ROOT=%NITROLIBVCT_ROOT%
set PATH=%PATH%;%NITROSYSTEM_ROOT%\tools\win\bin